[SETUP]
b12Hour=0
bBeepOn=1
bBrakeWarn=0
bScreenSave=0
bVideoOutput=0
bDateShow=1
bAnyKeyPowerUp=1
bBackOff=0
bEnableFrontCamera=0
backDump=3
bBackLine=0
bright=50
contrast=50
hue=50
saturation=50
colorLampMode=0
language=0
animationType=0
idleReturnTime=1000
vcomVoltage=51
wallPaper=2.jpg
bBackMute=1

videoOutputFormat=0
avddVoltage=50
wheelType=0

[CONFIG]
bArmBeep=0
bBackToMain=0
bBackToSource=1
bBackStopSource=0
bCapacitiveScreen=0
bFontBold=0
bEnableAddFont=0
bEnableCapture=0
bToastAsTip=1
mainID=0
maxVolume=30
uiType=2
uiBpp=24
uiID=1
photoConvertMode=1
usb0Speed=2
usb1Speed=2
screenResolution=1
supportLanguage=588552187
sourceValid=16733548  
saleArea=0
arrowKeyMode=5
maxVideoValue=100
saveMethod=1
brakeDetectGpio=-1
illDetectGpio=-1
usb0PowerGpio=103

defaultSource=MainSource
defaultInterface=

logoPassword=W12233
factoryPaswword=779822
logoCardName=F:
appUpdateFile=SKLF133.img
mcuUpdateFile=SKLMcu.bin

lvdsBits=8
bUseSoftReset=1
bUseUi1Config=1
[DEBUG]
bPrintLog=1
bPrintTouch=0
bPrintThreadCpuLoad=0
bUseLogBuffer=0

[MCU]
mcuChip=2
mcuSerialName=/dev/uart1

[CAN]
bArmCan=0
carType=0
canSerialName=

[ARM]
armVolGain=88
armChannelA=0

[AUDIO]
audioChip=3
subwoof=13
minVolDB=-39
initVolGain=113
audioI2cName=/dev/twi2

[STARTUP]
startUpDefVolume=20
startUpMinVolume=5
startUpMaxVolume=30
startUpDelayTime=500
startUpResume=1
startUpVideoPath=
startUpMaxTalkVolume=20

[RADIO]
bRadioBackgroundRun=1
bArmRadio=1
radioChannelA=0
radioVolGain=88
radioMaxDac=799072
radioModule=2
radioArea=0
fmStopValue=18
amStopValue=45
stOpenValue=20
fmAdjChannel=58
fmMultipath=10
fmDetuning=5
amDetuning=10
bAmLocEnable=0
bHaveRds=0
bRdsEnDefault=0
radioButtonType=0
bRadioBackgroundRun=1
bRadioSoundAtCarPlay=0
bSortFreq=0

radioResetGpio=105
rdsInterruptGpio=-1
radioI2cName=
bAmEnable=1

[CHINA]
FM1=9300,9300,9800,10000,10200,10600,10800,10,10,8750,10800
FM2=9300,9300,9800,10000,10200,10600,10800,10,10,8750,10800
FM3=9300,9300,9800,10000,10200,10600,10800,10,10,8750,10800
AM1=522,522,522,603,999,1404,1620,9,9
AM2=522,522,522,603,999,1404,1620,9,9

[DVD]
bArmDvd=1
bEnableDvd=1
bDvdInterlace=0
dvdVolGain=88
dvdChannelA=0
dvdChannelV=0
dvdVideoOffsetX=0
dvdVideoOffsetY=0

[BT]
btModule=1
btmChannelA=0
btVolume=20
btVolGain=90
btmVolGain=90
bBtMusicNeedConnect=1
btSerialName=
btCmdMicGain=AT#VN030606
btLocalName=CAR-BT
btPinCode=
bBtLocalNameUnique=1
btHeadsetSerialName=/dev/uart3
btHeadsetModule=0
btMicGain=13
btHeadsetMicGain=40

[MEDIA]
bEnableLicenseMedia=1
bMediaBackgroundPlay=0
bMediaSoftDecode=1
bDecodeHDPhoto=1
mediaMaxVol=100
mediaVolGain=88

mediaChannelA=0
mediaBright=46
mdiaConstast=47
mediaHue=50
mediaSaturation=91
videoZoomMode=0

usbDiskName=
usbDisk2Name=
sdCardName=
sdCard2Name=

[TV]
tvType=0
tvChannelA=0
tvChannelV=0

tvBright=46
tvConstast=47
tvHue=50
tvSaturation=91

tvVideoOffsetX=0
tvVideoOffsetY=0
tvSerialName=

[VIDEO]
auxVolGain=88
auxChannelA=1
aux2ChannelA=1
aux3ChannelA=11
;0=CVBS0,1=CVBS1,10=AHDIN0,11,12,13=AHDIN3
auxChannelV=0
aux2ChannelV=-1
aux3ChannelV=4
backChannelV=12
frontChannelV=10
videoPlayTime=500

videoBright=10
videoConstast=50
videoHue=0
videoSaturation=50

auxDetectGpio=-1
cameraSwitch1Gpio=-1
cameraSwitch2Gpio=-1
frontAuxSwitchGpio=407

auxVideoOffsetX=6
auxVideoOffsetY=0
auxVideoOffsetW=-8
auxVideoOffsetH=0
auxDetectGpio=-1
cameraSwitch1Gpio=-1
cameraSwitch2Gpio=-1
frontAuxSwitchGpio=102

[LINK]
bEchoCancel=1
echoDelayTime=200
echoCancelMode=4
bNoiseCancel=1
noiseCancelMode=3
bAutoGainCtrl=0
minAgcGain=0
maxAgcGain=15
noiseThreshold=150
micGain=70

usbIphoneLink=1
usbAndroidLink=2
carplayVolGain=88
carplayVolume=20
carplayIconLabel=
carplayI2cName=/dev/twi2
carplayCarName=AUTO BOX
wifiChannel=36
linkVolGain=88
androidWifiMode=2

[BACKLIGHT]
backLightGain=32
bBackLightReverse=0
bBackLightPowerCtrl=1
backLightMinValue=5
backLightMode=0
backLightDay=100
backLightNight=40
backLight=100

[TOUCH]
bTouchXYSwap=0
bTouchXReverse=1
bTouchYReverse=0
touchCalibData=
touchOriginX=0
touchOriginY=0

[MIC]
micCtrlType=0
micDetectGpio=-1
micSwitchGpio=-1
micSerialName=

[MAINKEY]
key0=44
key1=38
key2=29
key3=26
key4=48
key5=2567

[SCREENKEY]
button1X=829
button1Y=103
button1Key=16393
button2X=822
button2Y=270
button2Key=16392
button3X=829
button3Y=192
button3Key=16417
button4X=0
button4Y=0
button4Key=0
button5X=0
button5Y=0
button5Key=0
button6X=0
button6Y=0
button6Key=0
button7X=0
button7Y=0
button7Key=0
button8X=0
button8Y=0
button8Key=0
button9X=0
button9Y=0
button9Key=0
button10X=0
button10Y=0
button10Key=0

[PANELKEY1]
button1Volt=8
button1Key=224
button2Volt=20
button2Key=7
button3Volt=33
button3Key=32
button4Volt=50
button4Key=226


[PANELKEY2]
button1Volt=255
button1Key=0
button2Volt=255
button2Key=0
button3Volt=255
button3Key=0
button4Volt=255
button4Key=0
button5Volt=255
button5Key=0
button6Volt=255
button6Key=0
button7Volt=255
button7Key=0
button8Volt=255
button8Key=0
button9Volt=255
button9Key=0
button10Volt=255
button10Key=0
[IRKEY]
userCode=32640
button1Code=28
button1Key=224

button2Code=65
button2Key=12

button3Code=79
button3Key=7

button4Code=85
button4Key=6

button5Code=86
button5Key=2

button6Code=89
button6Key=3

button7Code=84
button7Key=4

button8Code=81
button8Key=36

button9Code=95
button9Key=127

button10Code=2
button10Key=90

button11Code=82
button11Key=37

button12Code=87
button12Key=35

button13Code=91
button13Key=63

button14Code=0
button14Key=0

button15Code=0
button15Key=0

button16Code=0
button16Key=0

[SCREEN]
refreshRate=30


[CAR]
seatRowNumber=0
seatColumnNumber=0

[GPS]
gpsVolGain=80
[CARRECODER]
carRecoderFileName = xhlwxf
